version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ixn
      POSTGRES_USER: dbuser  # TODO: use secrets
      POSTGRES_PASSWORD: dbpass  # TODO: use secrets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

