version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${IXN_POSTGRES_DB}
      POSTGRES_USER: ${IXN_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${IXN_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

