spring:
  security:
    user:
      name: x
      password: x
  datasource:
    url: jdbc:postgresql://localhost:5432/ixn
    username: dbuser  # TODO: use secrets
    password: dbpass  # TODO: use secrets
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Retains data
#      ddl-auto: create  # Drops all data

logging:
  level:
    root: INFO

data:
  initialize: false  # controls whether to init data in DataInitializer.java
#  initialize: true  # controls whether to init data in DataInitializer.java

# (spring.jpa.hibernate.ddl-auto, data.initialize)
# Normally: (update, false)
# Reset: (create, true)

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970