spring:
  security:
    user:
      name: x
      password: x
  datasource:
    url: jdbc:postgresql://${IXN_POSTGRES_HOST}:${IXN_POSTGRES_PORT}/ixn
    username: ${IXN_POSTGRES_USERNAME}
    password: ${IXN_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Retains data [STEP 1/2]
#      ddl-auto: create  # Drops all data [STEP 1/2]

logging:
  level:
    root: INFO

data:
  initialize: false  # controls whether to init data in DataInitializer.java [STEP 2/2]
#  initialize: true  # controls whether to init data in DataInitializer.java [STEP 2/2]

# (spring.jpa.hibernate.ddl-auto, data.initialize)
# Normally: (update, false)
# Reset: (create, true)

application:
  security:
    jwt:
      secret-key:
        ${IXN_APP_JWT_SECRET_KEY}